INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (1, 'Afghanistan', 'AF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (2, 'Åland Islands', 'AX', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (3, 'Albania', 'AL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (4, 'Algeria', 'DZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (5, 'American Samoa', 'AS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (6, 'Andorra', 'AD', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (7, 'Angola', 'AO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (8, 'Anguilla', 'AI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (9, 'Antarctica', 'AQ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (10, 'Antigua and Barbuda', 'AG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (11, 'Argentina', 'AR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (12, 'Armenia', 'AM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (13, 'Aruba', 'AW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (14, 'Australia', 'AU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (15, 'Austria', 'AT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (16, 'Azerbaijan', 'AZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (17, 'Bahamas', 'BS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (18, 'Bahrain', 'BH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (19, 'Bangladesh', 'BD', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (20, 'Barbados', 'BB', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (21, 'Belarus', 'BY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (22, 'Belgium', 'BE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (23, 'Belize', 'BZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (24, 'Benin', 'BJ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (25, 'Bermuda', 'BM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (26, 'Bhutan', 'BT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (27, 'Bolivia, Plurinational State of', 'BO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (28, 'Bonaire, Sint Eustatius and Saba', 'BQ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (29, 'Bosnia and Herzegovina', 'BA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (30, 'Botswana', 'BW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (31, 'Bouvet Island', 'BV', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (32, 'Brazil', 'BR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (33, 'British Indian Ocean Territory', 'IO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (34, 'Brunei Darussalam', 'BN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (35, 'Bulgaria', 'BG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (36, 'Burkina Faso', 'BF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (37, 'Burundi', 'BI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (38, 'Cambodia', 'KH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (39, 'Cameroon', 'CM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (40, 'Canada', 'CA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (41, 'Cape Verde', 'CV', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (42, 'Cayman Islands', 'KY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (43, 'Central African Republic', 'CF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (44, 'Chad', 'TD', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (45, 'Chile', 'CL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (46, 'China', 'CN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (47, 'Christmas Island', 'CX', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (48, 'Cocos (Keeling) Islands', 'CC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (49, 'Colombia', 'CO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (50, 'Comoros', 'KM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (51, 'Congo', 'CG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (52, 'Congo, the Democratic Republic of the', 'CD', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (53, 'Cook Islands', 'CK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (54, 'Costa Rica', 'CR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (55, 'Côte d\'Ivoire', 'CI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (56, 'Croatia', 'HR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (57, 'Cuba', 'CU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (58, 'Curaçao', 'CW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (59, 'Cyprus', 'CY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (60, 'Czech Republic', 'CZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (61, 'Denmark', 'DK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (62, 'Djibouti', 'DJ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (63, 'Dominica', 'DM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (64, 'Dominican Republic', 'DO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (65, 'Ecuador', 'EC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (66, 'Egypt', 'EG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (67, 'El Salvador', 'SV', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (68, 'Equatorial Guinea', 'GQ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (69, 'Eritrea', 'ER', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (70, 'Estonia', 'EE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (71, 'Ethiopia', 'ET', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (72, 'Falkland Islands (Malvinas)', 'FK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (73, 'Faroe Islands', 'FO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (74, 'Fiji', 'FJ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (75, 'Finland', 'FI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (76, 'France', 'FR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (77, 'French Guiana', 'GF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (78, 'French Polynesia', 'PF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (79, 'French Southern Territories', 'TF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (80, 'Gabon', 'GA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (81, 'Gambia', 'GM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (82, 'Georgia', 'GE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (83, 'Germany', 'DE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (84, 'Ghana', 'GH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (85, 'Gibraltar', 'GI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (86, 'Greece', 'GR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (87, 'Greenland', 'GL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (88, 'Grenada', 'GD', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (89, 'Guadeloupe', 'GP', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (90, 'Guam', 'GU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (91, 'Guatemala', 'GT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (92, 'Guernsey', 'GG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (93, 'Guinea', 'GN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (94, 'Guinea-Bissau', 'GW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (95, 'Guyana', 'GY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (96, 'Haiti', 'HT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (97, 'Heard Island and McDonald Mcdonald Islands', 'HM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (98, 'Holy See (Vatican City State)', 'VA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (99, 'Honduras', 'HN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (100, 'Hong Kong', 'HK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (101, 'Hungary', 'HU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (102, 'Iceland', 'IS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (103, 'India', 'IN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (104, 'Indonesia', 'ID', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (105, 'Iran, Islamic Republic of', 'IR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (106, 'Iraq', 'IQ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (107, 'Ireland', 'IE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (108, 'Isle of Man', 'IM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (109, 'Israel', 'IL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (110, 'Italy', 'IT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (111, 'Jamaica', 'JM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (112, 'Japan', 'JP', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (113, 'Jersey', 'JE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (114, 'Jordan', 'JO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (115, 'Kazakhstan', 'KZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (116, 'Kenya', 'KE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (117, 'Kiribati', 'KI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (118, 'Korea, Democratic People\'s Republic of', 'KP', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (119, 'Korea, Republic of', 'KR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (120, 'Kuwait', 'KW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (121, 'Kyrgyzstan', 'KG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (122, 'Lao People\'s Democratic Republic', 'LA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (123, 'Latvia', 'LV', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (124, 'Lebanon', 'LB', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (125, 'Lesotho', 'LS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (126, 'Liberia', 'LR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (127, 'Libya', 'LY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (128, 'Liechtenstein', 'LI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (129, 'Lithuania', 'LT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (130, 'Luxembourg', 'LU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (131, 'Macao', 'MO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (132, 'Macedonia, the Former Yugoslav Republic of', 'MK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (133, 'Madagascar', 'MG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (134, 'Malawi', 'MW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (135, 'Malaysia', 'MY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (136, 'Maldives', 'MV', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (137, 'Mali', 'ML', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (138, 'Malta', 'MT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (139, 'Marshall Islands', 'MH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (140, 'Martinique', 'MQ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (141, 'Mauritania', 'MR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (142, 'Mauritius', 'MU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (143, 'Mayotte', 'YT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (144, 'Mexico', 'MX', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (145, 'Micronesia, Federated States of', 'FM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (146, 'Moldova, Republic of', 'MD', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (147, 'Monaco', 'MC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (148, 'Mongolia', 'MN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (149, 'Montenegro', 'ME', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (150, 'Montserrat', 'MS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (151, 'Morocco', 'MA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (152, 'Mozambique', 'MZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (153, 'Myanmar', 'MM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (154, 'Namibia', 'NA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (155, 'Nauru', 'NR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (156, 'Nepal', 'NP', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (157, 'Netherlands', 'NL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (158, 'New Caledonia', 'NC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (159, 'New Zealand', 'NZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (160, 'Nicaragua', 'NI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (161, 'Niger', 'NE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (162, 'Nigeria', 'NG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (163, 'Niue', 'NU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (164, 'Norfolk Island', 'NF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (165, 'Northern Mariana Islands', 'MP', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (166, 'Norway', 'NO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (167, 'Oman', 'OM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (168, 'Pakistan', 'PK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (169, 'Palau', 'PW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (170, 'Palestine, State of', 'PS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (171, 'Panama', 'PA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (172, 'Papua New Guinea', 'PG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (173, 'Paraguay', 'PY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (174, 'Peru', 'PE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (175, 'Philippines', 'PH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (176, 'Pitcairn', 'PN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (177, 'Poland', 'PL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (178, 'Portugal', 'PT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (179, 'Puerto Rico', 'PR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (180, 'Qatar', 'QA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (181, 'Réunion', 'RE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (182, 'Romania', 'RO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (183, 'Russian Federation', 'RU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (184, 'Rwanda', 'RW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (185, 'Saint Barthélemy', 'BL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (186, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (187, 'Saint Kitts and Nevis', 'KN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (188, 'Saint Lucia', 'LC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (189, 'Saint Martin (French part)', 'MF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (190, 'Saint Pierre and Miquelon', 'PM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (191, 'Saint Vincent and the Grenadines', 'VC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (192, 'Samoa', 'WS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (193, 'San Marino', 'SM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (194, 'Sao Tome and Principe', 'ST', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (195, 'Saudi Arabia', 'SA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (196, 'Senegal', 'SN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (197, 'Serbia', 'RS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (198, 'Seychelles', 'SC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (199, 'Sierra Leone', 'SL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (200, 'Singapore', 'SG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (201, 'Sint Maarten (Dutch part)', 'SX', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (202, 'Slovakia', 'SK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (203, 'Slovenia', 'SI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (204, 'Solomon Islands', 'SB', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (205, 'Somalia', 'SO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (206, 'South Africa', 'ZA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (207, 'South Georgia and the South Sandwich Islands', 'GS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (208, 'South Sudan', 'SS', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (209, 'Spain', 'ES', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (210, 'Sri Lanka', 'LK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (211, 'Sudan', 'SD', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (212, 'Suriname', 'SR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (213, 'Svalbard and Jan Mayen', 'SJ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (214, 'Swaziland', 'SZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (215, 'Sweden', 'SE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (216, 'Switzerland', 'CH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (217, 'Syrian Arab Republic', 'SY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (218, 'Taiwan', 'TW', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (219, 'Tajikistan', 'TJ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (220, 'Tanzania, United Republic of', 'TZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (221, 'Thailand', 'TH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (222, 'Timor-Leste', 'TL', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (223, 'Togo', 'TG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (224, 'Tokelau', 'TK', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (225, 'Tonga', 'TO', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (226, 'Trinidad and Tobago', 'TT', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (227, 'Tunisia', 'TN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (228, 'Turkey', 'TR', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (229, 'Turkmenistan', 'TM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (230, 'Turks and Caicos Islands', 'TC', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (231, 'Tuvalu', 'TV', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (232, 'Uganda', 'UG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (233, 'Ukraine', 'UA', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (234, 'United Arab Emirates', 'AE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (235, 'United Kingdom', 'GB', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (236, 'United States', 'US', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (237, 'United States Minor Outlying Islands', 'UM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (238, 'Uruguay', 'UY', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (239, 'Uzbekistan', 'UZ', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (240, 'Vanuatu', 'VU', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (241, 'Venezuela, Bolivarian Republic of', 'VE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (242, 'Viet Nam', 'VN', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (243, 'Virgin Islands, British', 'VG', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (244, 'Virgin Islands, U.S.', 'VI', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (245, 'Wallis and Futuna', 'WF', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (246, 'Western Sahara', 'EH', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (247, 'Yemen', 'YE', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (248, 'Zambia', 'ZM', NOW(), NOW());
INSERT INTO `countries` (`id`, `name`, `code`, `created_at`, `updated_at`) VALUES (249, 'Zimbabwe', 'ZW', NOW(), NOW());